#!/usr/bin/env perl

if (@ARGV && $ARGV[0] eq '-h') {
  die "$0: Convert CSV input file to TSV\n";
}

use Text::CSV_XS;

my $csv_in = Text::CSV_XS->new ({ sep_char => "," });
my $csv_out = Text::CSV_XS->new ({ sep_char => "\t", eol => "\n" });

while (defined (my $line = <>)) {
  $csv_in->parse($line);
  my @parsed = $csv_in->fields();
  $csv_out->print(\*STDOUT, \@parsed);
}

close $fh_in;
close $fh_out;
